# coding: UTF-8
import logging
import requests
from abc import ABCMeta, abstractmethod
from typing import Any, List, Dict, Union, Optional, TypeVar, Tuple

from nicotools.utils import NTLogger, LogIn

DatabaseType = Dict[str, Dict[str, Union[int, str, List[str]]]]
LoggerType = TypeVar("LoggerType", bound=logging.Logger)

def print_info(queue: List[str], file_name: Optional[str]=...) -> None: ...


def get_infos(queue: List[str], logger: Optional[NTLogger] = ...) -> DatabaseType: ...
def t2filename(text: str) -> str: ...


class GetResources(LogIn, metaclass=ABCMeta):
    def __init__(self, auth, session: Optional[requests.Session] = ...,
                 logger: LoggerType = ...) -> None:
        super().__init__(auth, session, logger)
        self.database = ...  # type: Optional[DatabaseType]
        self.save_dir = ...  # type: str
        self.logger = ...  # type: Union[LoggerType, "AltLogger"]
        self.session = ...  # type: requests.Session
        ...
    def make_dir(self, save_dir: str) -> None: ...
    @abstractmethod
    def start(self, database: DatabaseType, save_dir: str) ->None: ...
    @abstractmethod
    def download(self, video_id: str) -> bool: ...


class GetVideos(GetResources):
    def __init__(self, auth: Tuple[Optional[str], Optional[str]]=...,
                 logger: Optional[NTLogger] = ...,
                 session: Optional[requests.Session]=...) -> None:
        super().__init__(auth, logger, session)
        self.widgets = ...  # type: List
        self.so_video_id = ...  # type: str
        ...
    def start(self, database: DatabaseType, save_dir: str) ->None: ...
    def download(self, video_id: str, chunk_size: int=...) -> bool: ...
    def make_file_name(self, video_id: str) -> str: ...


class GetThumbnails(GetResources):
    def __init__(self, auth: Tuple[Optional[str], Optional[str]]=...,
                 logger: Optional[NTLogger] = ...) -> None:
        super().__init__(auth, logger, None)
        ...
    def start(self, database: DatabaseType, save_dir: str) ->None: ...
    def _download(self, video_id: str, is_large: bool=..., retry: int=...) \
            -> Union[bool, requests.Response]: ...
    def download(self, video_id: str) -> bool: ...
    def make_file_name(self, video_id: str) -> str: ...


class GetComments(GetResources):
    def __init__(self, auth: Tuple[Optional[str], Optional[str]]=...,
                 logger: Optional[NTLogger] = ...,
                 session: Optional[requests.Session]=...) -> None:
        super().__init__(auth, session, logger)
        self.so_video_id = ...  # type: str
        ...
    def start(self, database: DatabaseType, save_dir: str, xml_mode: bool=...) ->None: ...
    def download(self, video_id: str, xml_mode: bool=...) -> bool: ...
    def get_thread_key(self, video_id: str, needs_key: str=...) -> str: ...
    def make_param_xml(self, user_id: str, thread_id: str) -> str: ...
    def make_param_json(self, official_video: bool, user_id: str, user_key: str, thread_id: str,
                        optional_thread_id: Optional[str]=...,
                        thread_key: Optional[str]=..., force_184: Optional[str]=...) -> List[Dict]: ...
    def make_file_name(self, video_id: str, xml_mode: bool=...) -> str: ...

def main(args: Any) -> None: ...
